# Covertype

Get to know the covertype dataset from UCI Irvine Machine learning repository

In [42]:
import os
import gzip

import pandas as pd
import numpy as np

import sklearn
from sklearn.model_selection import KFold, train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

In [27]:
sklearn.__version__

'0.19.1'

In [10]:
pd.set_option('display.max_columns', 80)

## Attributes

    Elevation                               quantitative    meters                       Elevation in meters
    Aspect                                  quantitative    azimuth                      Aspect in degrees azimuth
    Slope                                   quantitative    degrees                      Slope in degrees
    Horizontal_Distance_To_Hydrology        quantitative    meters                       Horz Dist to nearest surface water features
    Vertical_Distance_To_Hydrology          quantitative    meters                       Vert Dist to nearest surface water features
    Horizontal_Distance_To_Roadways         quantitative    meters                       Horz Dist to nearest roadway
    Hillshade_9am                           quantitative    0 to 255 index               Hillshade index at 9am, summer solstice
    Hillshade_Noon                          quantitative    0 to 255 index               Hillshade index at noon, summer soltice
    Hillshade_3pm                           quantitative    0 to 255 index               Hillshade index at 3pm, summer solstice
    Horizontal_Distance_To_Fire_Points      quantitative    meters                       Horz Dist to nearest wildfire ignition points
    Wilderness_Area (4 binary columns)      qualitative     0 (absence) or 1 (presence)  Wilderness area designation
    Soil_Type (40 binary columns)           qualitative     0 (absence) or 1 (presence)  Soil Type designation
    Cover_Type (7 types)                    integer         1 to 7                       Forest Cover 

In [2]:
colnames_and_numcols = (
    ('Elevation', 1),
    ('Aspect', 1),
    ('Slope', 1),
    ('Horizontal_Distance_To_Hydrology', 1),
    ('Vertical_Distance_To_Hydrology', 1),
    ('Horizontal_Distance_To_Roadways', 1),
    ('Hillshade_9am', 1),
    ('Hillshade_Noon', 1),
    ('Hillshade_3pm', 1),
    ('Horizontal_Distance_To_Fire_Points', 1),
    ('Wilderness_Area', 4),
    ('Soil_Type', 40),
    ('Cover_Type', 1),
)

In [3]:
colnames = []
for colname, numcols in colnames_and_numcols:
    if numcols > 1:
        for i in range(numcols):
            colnames.append('{}_{}'.format(colname, i))
    else:
        colnames.append(colname)

In [4]:
colnames

['Elevation',
 'Aspect',
 'Slope',
 'Horizontal_Distance_To_Hydrology',
 'Vertical_Distance_To_Hydrology',
 'Horizontal_Distance_To_Roadways',
 'Hillshade_9am',
 'Hillshade_Noon',
 'Hillshade_3pm',
 'Horizontal_Distance_To_Fire_Points',
 'Wilderness_Area_0',
 'Wilderness_Area_1',
 'Wilderness_Area_2',
 'Wilderness_Area_3',
 'Soil_Type_0',
 'Soil_Type_1',
 'Soil_Type_2',
 'Soil_Type_3',
 'Soil_Type_4',
 'Soil_Type_5',
 'Soil_Type_6',
 'Soil_Type_7',
 'Soil_Type_8',
 'Soil_Type_9',
 'Soil_Type_10',
 'Soil_Type_11',
 'Soil_Type_12',
 'Soil_Type_13',
 'Soil_Type_14',
 'Soil_Type_15',
 'Soil_Type_16',
 'Soil_Type_17',
 'Soil_Type_18',
 'Soil_Type_19',
 'Soil_Type_20',
 'Soil_Type_21',
 'Soil_Type_22',
 'Soil_Type_23',
 'Soil_Type_24',
 'Soil_Type_25',
 'Soil_Type_26',
 'Soil_Type_27',
 'Soil_Type_28',
 'Soil_Type_29',
 'Soil_Type_30',
 'Soil_Type_31',
 'Soil_Type_32',
 'Soil_Type_33',
 'Soil_Type_34',
 'Soil_Type_35',
 'Soil_Type_36',
 'Soil_Type_37',
 'Soil_Type_38',
 'Soil_Type_39',
 'Cov

In [5]:
len(colnames)

55

In [6]:
data_path = '~/Documents/datasets/uci/covertype/covtype.data.gz'

In [7]:
with gzip.open(os.path.expanduser(data_path)) as f:
    df = pd.read_csv(f, names=colnames)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 581012 entries, 0 to 581011
Data columns (total 55 columns):
Elevation                             581012 non-null int64
Aspect                                581012 non-null int64
Slope                                 581012 non-null int64
Horizontal_Distance_To_Hydrology      581012 non-null int64
Vertical_Distance_To_Hydrology        581012 non-null int64
Horizontal_Distance_To_Roadways       581012 non-null int64
Hillshade_9am                         581012 non-null int64
Hillshade_Noon                        581012 non-null int64
Hillshade_3pm                         581012 non-null int64
Horizontal_Distance_To_Fire_Points    581012 non-null int64
Wilderness_Area_0                     581012 non-null int64
Wilderness_Area_1                     581012 non-null int64
Wilderness_Area_2                     581012 non-null int64
Wilderness_Area_3                     581012 non-null int64
Soil_Type_0                           581012 non-

In [11]:
df.head()

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0       2596      51      3                               258   
1       2590      56      2                               212   
2       2804     139      9                               268   
3       2785     155     18                               242   
4       2595      45      2                               153   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                               0                              510   
1                              -6                              390   
2                              65                             3180   
3                             118                             3090   
4                              -1                              391   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
0            221             232            148   
1            220             235            151   
2            234             238            135   
3            238             238            122   
4            220             234            150   

   Horizontal_Distance_To_Fire_Points  Wilderness_Area_0  Wilderness_Area_1  \
0                                6279                  1                  0   
1                                6225                  1                  0   
2                                6121                  1                  0   
3                                6211                  1                  0   
4                                6172                  1                  0   

   Wilderness_Area_2  Wilderness_Area_3  Soil_Type_0  Soil_Type_1  \
0                  0                  0            0            0   
1                  0                  0            0            0   
2                  0                  0            0            0   
3                  0                  0            0            0   
4                  0                  0            0            0   

   Soil_Type_2  Soil_Type_3  Soil_Type_4  Soil_Type_5  Soil_Type_6  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type_7  Soil_Type_8  Soil_Type_9  Soil_Type_10  Soil_Type_11  \
0            0            0            0             0             0   
1            0            0            0             0             0   
2            0            0            0             0             1   
3            0            0            0             0             0   
4            0            0            0             0             0   

   Soil_Type_12  Soil_Type_13  Soil_Type_14  Soil_Type_15  Soil_Type_16  \
0             0             0             0             0             0   
1             0             0             0             0             0   
2             0             0             0             0             0   
3             0             0             0             0             0   
4             0             0             0             0             0   

   Soil_Type_17  Soil_Type_18  Soil_Type_19  Soil_Type_20  Soil_Type_21  \
0             0             0             0             0             0   
1             0             0             0             0             0   
2             0             0             0             0             0   
3             0             0             0             0             0   
4             0             0             0             0             0   

   Soil_Type_22  Soil_Type_23  Soil_Type_24  Soil_Type_25  Soil_Type_26  \
0             0             0             0             0             0   
1             0             0             0             0             0   
2            

In [12]:
df.describe()

Elevation         Aspect          Slope  \
count  581012.000000  581012.000000  581012.000000   
mean     2959.365301     155.656807      14.103704   
std       279.984734     111.913721       7.488242   
min      1859.000000       0.000000       0.000000   
25%      2809.000000      58.000000       9.000000   
50%      2996.000000     127.000000      13.000000   
75%      3163.000000     260.000000      18.000000   
max      3858.000000     360.000000      66.000000   

       Horizontal_Distance_To_Hydrology  Vertical_Distance_To_Hydrology  \
count                     581012.000000                   581012.000000   
mean                         269.428217                       46.418855   
std                          212.549356                       58.295232   
min                            0.000000                     -173.000000   
25%                          108.000000                        7.000000   
50%                          218.000000                       30.000000   
75%                          384.000000                       69.000000   
max                         1397.000000                      601.000000   

       Horizontal_Distance_To_Roadways  Hillshade_9am  Hillshade_Noon  \
count                    581012.000000  581012.000000   581012.000000   
mean                       2350.146611     212.146049      223.318716   
std                        1559.254870      26.769889       19.768697   
min                           0.000000       0.000000        0.000000   
25%                        1106.000000     198.000000      213.000000   
50%                        1997.000000     218.000000      226.000000   
75%                        3328.000000     231.000000      237.000000   
max                        7117.000000     254.000000      254.000000   

       Hillshade_3pm  Horizontal_Distance_To_Fire_Points  Wilderness_Area_0  \
count  581012.000000                       581012.000000      581012.000000   
mean      142.528263                         1980.291226           0.448865   
std        38.274529                         1324.195210           0.497379   
min         0.000000                            0.000000           0.000000   
25%       119.000000                         1024.000000           0.000000   
50%       143.000000                         1710.000000           0.000000   
75%       168.000000                         2550.000000           1.000000   
max       254.000000                         7173.000000           1.000000   

       Wilderness_Area_1  Wilderness_Area_2  Wilderness_Area_3    Soil_Type_0  \
count      581012.000000      581012.000000      581012.000000  581012.000000   
mean            0.051434           0.436074           0.063627       0.005217   
std             0.220882           0.495897           0.244087       0.072039   
min             0.000000           0.000000           0.000000       0.000000   
25%             0.000000           0.000000           0.000000       0.000000   
50%             0.000000           0.000000           0.000000       0.000000   
75%             0.000000           1.000000           0.000000       0.000000   
max             1.000000           1.000000           1.000000       1.000000   

         Soil_Type_1    Soil_Type_2    Soil_Type_3    Soil_Type_4  \
count  581012.000000  581012.000000  581012.000000  581012.000000   
mean        0.012952       0.008301       0.021335       0.002749   
std         0.113066       0.090731       0.144499       0.052356   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

         Soil_Type_5    Soil_Type_6    Soil_Type_7    Soil_Type_8  \
count  581012.000000  581012.000000  581012.000000  58101

In [16]:
df.isnull().sum()

Elevation                             0
Aspect                                0
Slope                                 0
Horizontal_Distance_To_Hydrology      0
Vertical_Distance_To_Hydrology        0
Horizontal_Distance_To_Roadways       0
Hillshade_9am                         0
Hillshade_Noon                        0
Hillshade_3pm                         0
Horizontal_Distance_To_Fire_Points    0
Wilderness_Area_0                     0
Wilderness_Area_1                     0
Wilderness_Area_2                     0
Wilderness_Area_3                     0
Soil_Type_0                           0
Soil_Type_1                           0
Soil_Type_2                           0
Soil_Type_3                           0
Soil_Type_4                           0
Soil_Type_5                           0
Soil_Type_6                           0
Soil_Type_7                           0
Soil_Type_8                           0
Soil_Type_9                           0
Soil_Type_10                          0


In [18]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=5, stratify=y)

In [52]:
clf = SGDClassifier(sloss='log')

TypeError: __init__() got an unexpected keyword argument 'sloss'

In [53]:
clf.fit(X_train, y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='log', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [54]:
yhat = clf.predict(X_test)

In [55]:
yhat

array([5, 5, 5, ..., 5, 5, 5])

In [56]:
yprob = clf.predict_proba(X_test)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/base.py:340: RuntimeWarning: overflow encountered in exp
  np.exp(prob, prob)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/base.py:347: RuntimeWarning: invalid value encountered in true_divide
  prob /= prob.sum(axis=1).reshape((prob.shape[0], -1))


In [57]:
yprob.shape

(191734, 7)

In [58]:
yprob[0, :]

array([ nan,  nan,  nan,  nan,  nan,  nan,  nan])

In [59]:
yprob[1, :]

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.])

In [60]:
yprob.sum(axis=0)

array([ nan,  nan,  nan,  nan,  nan,  nan,  nan])

In [61]:
precision, recall, fscore, support = metrics.precision_recall_fscore_support(y_test, yhat)

/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [62]:
precision

array([ 0.75      ,  0.94047619,  0.72193331,  0.        ,  0.01662212,
        0.        ,  0.40909091])

In [63]:
recall

array([  9.44111462e-04,   8.45019200e-04,   2.00016951e-01,
         0.00000000e+00,   9.98404086e-01,   0.00000000e+00,
         6.64893617e-03])

In [64]:
fscore

array([ 0.00188585,  0.00168852,  0.31324662,  0.        ,  0.03269983,
        0.        ,  0.0130852 ])

In [50]:
y.value_counts()

2    283301
1    211840
3     35754
7     20510
6     17367
5      9493
4      2747
Name: Cover_Type, dtype: int64